controller_manager:
  ros__parameters:
    update_rate: 150  #Hz
    is_async: True

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_current_controller:
      type: forward_command_controller/ForwardCommandController

    udwadia_kalaba_controller:
      type: udwadia_kalaba_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: velocity

forward_current_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: current

udwadia_kalaba_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: current

