controller_manager:
  ros__parameters:
    update_rate: 225  #Hz

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_current_controller:
      type: forward_command_controller/ForwardCommandController

    forward_illegal1_controller:
      type: forward_command_controller/ForwardCommandController

    forward_illegal2_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

forward_position_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: velocity

forward_current_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: current

forward_illegal1_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
    interface_name: position

forward_illegal2_controller:
  ros__parameters:
    joints:
      - alpha_axis_b
    interface_name: position

