controller_manager:
  ros__parameters:
    update_rate: 150  #Hz
    is_async: True

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_current_controller:
      type: forward_command_controller/ForwardCommandController

    forward_effort_controller:
      type: forward_command_controller/ForwardCommandController

    free_excitation_controller:
      type: forward_command_controller/ForwardCommandController

    udwadia_kalaba_controller:
      type: udwadia_kalaba_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

joint_state_broadcaster:
  ros__parameters:
    map_interface_to_joint_state:
      effort: effort
      position: position
      velocity: velocity
      acceleration: acceleration
      current: current
      stateId: stateId

forward_position_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: velocity

forward_current_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: current

forward_effort_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: effort

udwadia_kalaba_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    command_interface_name: current
    state_interface_names: 
      - position
      - velocity


free_excitation_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: excite